### ISSUE TITLE
Recipes don't work

### ISSUE THREAD

**Issue by Zkaface** [Darkhax-Minecraft/Enchanting-Plus#28]
Neither is JEI able to show a recipe of this mod, nor are we able to craft any item. We just tested with your shown recipes on curseforge.

No Errors in Client or Server console.

Forge Version: forge-1.9-12.16.0.1865

**Comment by InsydeH20** [comment]
I am having the same issue like yours and i have NO IDEA how to fix it. I also cannot enchant in survival but i can in creative. I really hope that  you , me and the people having the same issue can get help...

**Comment by darkhax** [comment]
Recipes do not work because they are not added to the game yet. The 1.9 releases are alpha releases and meant to test for specific issues. This is currently early into the development cycle, so it should not be expected for this mod to work in a survival setting. 

I am keeping this issue open, and it will be closed when the recipes are added back in.

**Comment by darkhax** [comment]
Recipes for the table upgrade, the eplus table, the decorative book and the shapeless recipe have been added back in. The mod is still not ready for survival play yet.
