### ISSUE TITLE
Cannot build from master

### ISSUE THREAD

**Issue by rastamanfb** [Darkhax-Minecraft/Enchanting-Plus#29]
*****\Enchanting-Plus-master>gradlew build

FAILURE: Build failed with an exception.

* Where:
Build file '*****\Downloads\Enchanting-Plus-master\Enchanting-Plus-master\build.gradle' line: 161

* What went wrong:
A problem occurred evaluating root project 'Enchanting-Plus-master'.
> Cannot run program "git": CreateProcess error=2, The system cannot find the file specified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.127 secs

********\Downloads\Enchanting-Plus-master\Enchanting-Plus-master>

**Comment by darkhax** [comment]
Thank you for reporting this issue. The issue was the result of git not being installed, which was needed by the build script. As of ab2c6f14c9cf83a252336f614d35ffa04807a8c7 this is no longer required. 

I am curious why you are trying to build the project, the compiled mod, deobf jar, sources and JavaDocs are all uploaded to [CurseForge](http://minecraft.curseforge.com/projects/enchanting-plus/files) automatically when someone makes a change to the mod.

**Comment by rastamanfb** [comment]
Cos im nuts :) i just noticed there was a load of commits made recently yet
the version on Curse for 1.7.10 is still rc3 from December last year.

I wanted to compile to see what version came through and see if that fixed
issues that im seeing in 74rc3

**Comment by darkhax** [comment]
Which issues are you seeing in 74rc3?

**Comment by rastamanfb** [comment]
The closed one i am replying to you on with ignored false value for scrolls

**Comment by darkhax** [comment]
Ah, okay.
