### ISSUE TITLE
Balancing Issues

### ISSUE THREAD

**Issue by HalfOfAKebab** [Darkhax-Minecraft/Enchanting-Plus#52]
This has major balancing issues. If I enchant a sword with Sharpness V and the highest level of every other compatible enchantment, the cost is 93 levels. However, I can apply each enchantment individually and the total will still be 93. This is very bad for balancing, since getting from level 15 to 16 is easier than 16 to 17, which means the enchantments you need are a lot cheaper if you apply them individually.

To fix this, the mod's enchantment table should take experience points rather than the level.

**Comment by odininon** [comment]
This has been an issue since I took over back in 1.3.2. Coming up with a decent algorithm that works is quite challenging. 

I do like the idea of just using straight up experience points. This however goes against how the vanilla table works, so we could do experience points on the backend yet still display experience levels on the GUIs.

**Comment by HalfOfAKebab** [comment]
You could calculate it through XP, and then round it up to the next level? I think this would be a very balanced and still vanilla approach.

**Comment by darkhax** [comment]
The system already uses xp rather than levels on the back end, perhaps there is an issue with the display.

**Comment by darkhax** [comment]
This is fixed in the current 1.12.2 beta. More info on how it was fixed [here](https://github.com/Darkhax-Minecraft/Enchanting-Plus/issues/89)
